[package]
name = "test_sync"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_sync"

[dependencies]
axum = "0.7.5"
notify = "6.1.1"
clap = { version = "4.5.7", features = ["cargo"] }
tokio = { version = "1.38.0", features = ["full"] }
serde_json = "1.0.117"
